### ISSUE TITLE
Train got error died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by dixingxing0** [alibaba/HybridBackend#153]
# Current behavior
Got error:
```
2023-10-16 16:57:39.928906: E hybridbackend/tensorflow/distribute/nccl/nccl_collective.cc:461] NCCL communication aborted: unhandled system error
2023-10-16 16:57:40.323595: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at nccl_create.cc:112 : Internal: unhandled system error
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'tensorflow.python.distribute.launch' found in sys.modules after import of package 'tensorflow.python.distribute', but prior to execution of 'tensorflow.python.distribute.launch'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/distribute/launch.py", line 319, in <module>
launch([args.command] + args.args)
File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/distribute/launch.py", line 97, in launch
subprocess.check_call(command)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'run.py', '--worker_index=0', '--worker_size=4', '--protocol=grpc']' died with <Signals.SIGSEGV: 11>.
```

# Expected behavior
Train without error

# System information
- GPU model and memory: 
- OS Platform:
- Docker version:
- GCC/CUDA/cuDNN version: CUDA 11.6
- Python/conda version:
- TensorFlow + DeepRec version: 1.15.5+deeprec2306
- HybridBackend hybridbackend-deeprec-cu116 1.0.0

# Code to reproduce

```python

from tensorflow.python.distribute.group_embedding_collective_strategy import CollectiveStrategy
strategy = CollectiveStrategy()
with strategy.scope(), tf.Graph().as_default():
	.....

// Run under: COLLECTIVE_STRATEGY=hb 
```
GPU memory : 16GB
Container memory : 100GB 

Launch command：
```
cd ./model;export JEMALLOC_VERSION=./model/libjemalloc.so.2.5.1;export MALLOC_CONF=background_thread:true,metadata_thp:auto,dirty_decay_ms:60000,muzzy_decay_ms:60000;LD_PRELOAD=${JEMALLOC_VERSION} COLLECTIVE_STRATEGY=hb $(which python) -m tensorflow.python.distribute.launch $(which python) -u run.py --worker_index=0 --worker_size=4 --protocol=grpc
```

After we reduce the batchSize from 4096 to 512， we train success with 1 chief and 1 worker；but we train fail with 1 chied and 3 workers.

More details: https://doc.autohome.com.cn/docapi/page/share/share_plYFxLWnVA

# Willing to contribute

Yes

**Comment by francktcheng** [comment]
why this issue is opened again? Increasing the shm size does not fix this crash?

**Comment by dixingxing0** [comment]
Yes, that can not fix this issue, and we also submit an issue in NVIDIA community : https://github.com/NVIDIA/nccl/issues/1039

**Comment by dixingxing0** [comment]
@francktcheng  docker image hybridbackend:1.0.0-deeprec-py3.6-cu114-ubuntu18.04-v1030 works fine, i will close this issue.
